apiVersion: v1
kind: Secret
metadata:
  name: {{ template "demo.fullname" . }}
  labels:
    app: {{ template "demo.name" . }}
    chart: {{ template "demo.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  ConnectionStrings__Default: {{.Values.env.connectionStrings.default | trimAll "\"" | b64enc | quote}}