name: ci

on:
  push:
    branches:
      - release
    tags:
      - "v*"
    paths:
      - "modules/account/**"
      - "charts/account/**"
  pull_request:
    branches:
      - main
    paths:
      - "modules/account/**"
      - "charts/account/**"

env:
  IMAGE_NAME: chaldea/fate-ci-demo
  SOLUTION_PATH: ./modules/account
  CHART_PATH: ./charts/account
  VERSION: 0.1.0

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker Build
        run: echo Docker build

  deployment:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - uses: actions/checkout@v1
      - name: Tag Version
        run: |
          TAG_VERSION=$(git describe --tags --abbrev=0 --match=v*[0-9.])
          if [ $? -eq 0 ]; then
            VERSION=${TAG_VERSION:1}
          fi
      - name: Docker Push
        run: |
          echo Docker build, tag: $IMAGE_NAME:v$VERSION-${github.run_number}

  package:
    if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/release' }}
    runs-on: ubuntu-latest
    needs: [testing, deployment]
    steps:
      - uses: actions/checkout@v1
      - name: Helm package
        run: |  
          echo Helm package