name: ci

on:
  push:
    branches:
      - release
    tags:
      - "v*"
    paths:
      - "modules/account/**"
      - "charts/account/**"
  pull_request:
    branches:
      - main
    paths:
      - "modules/account/**"
      - "charts/account/**"

env:
  IMAGE_NAME: chaldea/fate-ci-demo
  SOLUTION_PATH: ./modules/account
  CHART_PATH: ./charts/account
  VERSION: 0.1.0

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker Build
        run: echo "Testing"
        # run: docker build -f $SOLUTION_PATH/Dockerfile -t $IMAGE_NAME $SOLUTION_PATH

  deployment:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - uses: actions/checkout@v1
      - name: Get Version
        id: get-version
        run: |
          TAG=$(git describe --tags --abbrev=0 --match=v*[0-9.])
          if [ $? -eq 0 ]; then
            VERSION=${TAG:1}
          fi
          if [ "${{ github.ref }}" == "refs/heads/release" ]
          then
            echo '::set-output name=IMAGE_TAG::$IMAGE_NAME:$VERSION-$GITHUB_RUN_NUMBER'
          else
            echo '::set-output name=IMAGE_TAG::$IMAGE_NAME:$VERSION'
          if
          echo '::set-output name=VERSION::$VERSION'
      - name: Docker Build
        run: |
          echo "Tag: ${{ steps.get-version.outputs.VERSION }}"
          echo "Tag: ${{ steps.get-version.outputs.IMAGE_TAG }}"

  package:
    if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/release' }}
    runs-on: ubuntu-latest
    needs: [testing, deployment]
    steps:
      - uses: actions/checkout@v1
      - name: Helm package
        run: |  
          echo Helm package