name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Version
        id: auto-version
        uses: paulhatch/semantic-version@v4.0.1
        with:
          change_path: "main"
          tag_prefix: "v"
          minor_pattern: "(MINOR)"
          major_pattern: "(MAJOR)"
          format: "${major}.${minor}.${patch}"
          bump_each_commit: true
      - name: publish
        run: |
          echo ${{ steps.auto-version.outputs.version }}
          echo ${{ steps.auto-version.outputs.changed }}
          echo ${{ steps.auto-version.outputs.increment }}